name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: order_system_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Specify your PHP version
          extensions: mbstring, xml, curl, gd, bcmath, sqlite3, mysqli

      - name: Install Composer dependencies
        run: composer install

      - name: Set up Laravel environment variables
        run: |
          php artisan key:generate
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=order_system_test" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=root" >> .env

      - name: Run Database Migrations
        run: php artisan migrate --env=testing --force

      - name: Run Tests
        run: php artisan test

      - name: Cache Config
        run: php artisan config:cache

      - name: Cache Routes
        run: php artisan route:cache
